package Lab05;

public enum TokenName {
    KEYWORD_IF,
    KEYWORD_THEN,
    KEYWORD_REPEAT,
    KEYWORD_UNTIL,
    KEYWORD_OR,
    KEYWORD_FOR,
    KEYWORD_TO,
    KEYWORD_DO,
    KEYWORD_BEGIN,
    KEYWORD_END,
    IDENTIFIER, LITERAL, LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON, COLON, ASTERISK, ASSIGN, ADDITION, SUBTRACTION, OBELISK, EQUAL, NOT_EQUAL,
    SYMBOL_MORE, SYMBOL_LESS, UNDEFINED
}
