package Lab03;

public enum TokenName {
    KEYWORD, IDENTIFIER, LITERAL, LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON, COLON, ASTERISK, ASSIGN, ADDITION, SUBTRACTION, OBELISK, EQUAL, NOT_EQUAL,
    SYMBOL_MORE, SYMBOL_LESS, UNDEFINED
}
